<?php
if(class_exists("WooCommerce")) {
    class ET_WC_Package extends WC_Product
    {
        protected $etPaynentPackage;

        function __construct($product, $arg = array())
        {
            $this->product_type = 'payment_package';
            parent::__construct($product);
        }

        public function get_post_data()
        {
            return parent::get_post_data(); // TODO: Change the autogenerated stub
        }

        public function get_gallery_attachment_ids()
        {
            return parent::get_gallery_attachment_ids(); // TODO: Change the autogenerated stub
        }

        public function get_permalink()
        {
            return parent::get_permalink(); // TODO: Change the autogenerated stub
        }

        public function get_sku()
        {
            return $this->post->ID;
        }

        public function get_stock_quantity()
        {
            return parent::get_stock_quantity(); // TODO: Change the autogenerated stub
        }

        public function get_total_stock()
        {
            return parent::get_total_stock(); // TODO: Change the autogenerated stub
        }

        protected function check_stock_status()
        {
            parent::check_stock_status(); // TODO: Change the autogenerated stub
        }

        public function set_stock($amount = null, $mode = 'set')
        {
            return parent::set_stock($amount, $mode); // TODO: Change the autogenerated stub
        }

        public function reduce_stock($amount = 1)
        {
            return parent::reduce_stock($amount); // TODO: Change the autogenerated stub
        }

        public function increase_stock($amount = 1)
        {
            return parent::increase_stock($amount); // TODO: Change the autogenerated stub
        }

        public function set_stock_status($status)
        {
            parent::set_stock_status($status); // TODO: Change the autogenerated stub
        }

        public function is_type($type)
        {
            return parent::is_type($type); // TODO: Change the autogenerated stub
        }

        public function is_downloadable()
        {
            return parent::is_downloadable(); // TODO: Change the autogenerated stub
        }

        public function has_file($download_id = '')
        {
            return parent::has_file($download_id); // TODO: Change the autogenerated stub
        }

        public function get_files()
        {
            return parent::get_files(); // TODO: Change the autogenerated stub
        }

        public function get_file($download_id = '')
        {
            return parent::get_file($download_id); // TODO: Change the autogenerated stub
        }

        public function get_file_download_path($download_id)
        {
            return parent::get_file_download_path($download_id); // TODO: Change the autogenerated stub
        }

        public function is_virtual()
        {
            return true;
        }

        public function needs_shipping()
        {
            return false;
        }

        public function is_sold_individually()
        {
            return parent::is_sold_individually(); // TODO: Change the autogenerated stub
        }

        public function get_children()
        {
            return parent::get_children(); // TODO: Change the autogenerated stub
        }

        public function has_child()
        {
            return parent::has_child(); // TODO: Change the autogenerated stub
        }

        public function exists()
        {
            return parent::exists(); // TODO: Change the autogenerated stub
        }

        public function is_taxable()
        {
            return parent::is_taxable(); // TODO: Change the autogenerated stub
        }

        public function is_shipping_taxable()
        {
            return parent::is_shipping_taxable(); // TODO: Change the autogenerated stub
        }

        public function get_title()
        {
            return parent::get_title(); // TODO: Change the autogenerated stub
        }

        public function get_parent()
        {
            return parent::get_parent(); // TODO: Change the autogenerated stub
        }

        public function add_to_cart_url()
        {
            return parent::add_to_cart_url(); // TODO: Change the autogenerated stub
        }

        public function single_add_to_cart_text()
        {
            return parent::single_add_to_cart_text(); // TODO: Change the autogenerated stub
        }

        public function add_to_cart_text()
        {
            return parent::add_to_cart_text(); // TODO: Change the autogenerated stub
        }

        public function managing_stock()
        {
            return parent::managing_stock(); // TODO: Change the autogenerated stub
        }

        public function is_in_stock()
        {
            return parent::is_in_stock(); // TODO: Change the autogenerated stub
        }

        public function backorders_allowed()
        {
            return parent::backorders_allowed(); // TODO: Change the autogenerated stub
        }

        public function backorders_require_notification()
        {
            return parent::backorders_require_notification(); // TODO: Change the autogenerated stub
        }

        public function is_on_backorder($qty_in_cart = 0)
        {
            return parent::is_on_backorder($qty_in_cart); // TODO: Change the autogenerated stub
        }

        public function has_enough_stock($quantity)
        {
            return parent::has_enough_stock($quantity); // TODO: Change the autogenerated stub
        }

        public function get_availability()
        {
            return parent::get_availability(); // TODO: Change the autogenerated stub
        }

        public function is_featured()
        {
            return parent::is_featured(); // TODO: Change the autogenerated stub
        }

        public function is_visible()
        {
            return parent::is_visible(); // TODO: Change the autogenerated stub
        }

        public function is_on_sale()
        {
            return parent::is_on_sale(); // TODO: Change the autogenerated stub
        }

        public function get_weight()
        {
            return parent::get_weight(); // TODO: Change the autogenerated stub
        }

        public function is_purchasable()
        {
            return parent::is_purchasable(); // TODO: Change the autogenerated stub
        }

        public function set_price($price)
        {
            parent::set_price($price); // TODO: Change the autogenerated stub
        }

        public function adjust_price($price)
        {
            parent::adjust_price($price); // TODO: Change the autogenerated stub
        }

        public function get_sale_price()
        {
            return parent::get_sale_price(); // TODO: Change the autogenerated stub
        }

        public function get_regular_price()
        {
            return parent::get_regular_price(); // TODO: Change the autogenerated stub
        }

        public function get_price()
        {
            return parent::get_price(); // TODO: Change the autogenerated stub
        }

        public function get_price_including_tax($qty = 1, $price = '')
        {
            return parent::get_price_including_tax($qty, $price); // TODO: Change the autogenerated stub
        }

        public function get_price_excluding_tax($qty = 1, $price = '')
        {
            return parent::get_price_excluding_tax($qty, $price); // TODO: Change the autogenerated stub
        }

        public function get_price_suffix()
        {
            return parent::get_price_suffix(); // TODO: Change the autogenerated stub
        }

        public function get_price_html($price = '')
        {
            return parent::get_price_html($price); // TODO: Change the autogenerated stub
        }

        public function get_price_html_from_text()
        {
            return parent::get_price_html_from_text(); // TODO: Change the autogenerated stub
        }

        public function get_price_html_from_to($from, $to)
        {
            return parent::get_price_html_from_to($from, $to); // TODO: Change the autogenerated stub
        }

        public function get_tax_class()
        {
            return parent::get_tax_class(); // TODO: Change the autogenerated stub
        }

        public function get_tax_status()
        {
            return parent::get_tax_status(); // TODO: Change the autogenerated stub
        }

        public function get_average_rating()
        {
            return parent::get_average_rating(); // TODO: Change the autogenerated stub
        }

        public function get_rating_count($value = null)
        {
            return parent::get_rating_count($value); // TODO: Change the autogenerated stub
        }

        public function get_rating_html($rating = null)
        {
            return parent::get_rating_html($rating); // TODO: Change the autogenerated stub
        }

        public function get_upsells()
        {
            return parent::get_upsells(); // TODO: Change the autogenerated stub
        }

        public function get_cross_sells()
        {
            return parent::get_cross_sells(); // TODO: Change the autogenerated stub
        }

        public function get_categories($sep = ', ', $before = '', $after = '')
        {
            return parent::get_categories($sep, $before, $after); // TODO: Change the autogenerated stub
        }

        public function get_tags($sep = ', ', $before = '', $after = '')
        {
            return parent::get_tags($sep, $before, $after); // TODO: Change the autogenerated stub
        }

        public function get_shipping_class()
        {
            return parent::get_shipping_class(); // TODO: Change the autogenerated stub
        }

        public function get_shipping_class_id()
        {
            return parent::get_shipping_class_id(); // TODO: Change the autogenerated stub
        }

        public function get_related($limit = 5)
        {
            return parent::get_related($limit); // TODO: Change the autogenerated stub
        }

        public function get_attribute($attr)
        {
            return parent::get_attribute($attr); // TODO: Change the autogenerated stub
        }

        public function get_attributes()
        {
            return parent::get_attributes(); // TODO: Change the autogenerated stub
        }

        public function has_attributes()
        {
            return parent::has_attributes(); // TODO: Change the autogenerated stub
        }

        public function enable_dimensions_display()
        {
            return parent::enable_dimensions_display(); // TODO: Change the autogenerated stub
        }

        public function has_dimensions()
        {
            return parent::has_dimensions(); // TODO: Change the autogenerated stub
        }

        public function has_weight()
        {
            return parent::has_weight(); // TODO: Change the autogenerated stub
        }

        public function get_dimensions()
        {
            return parent::get_dimensions(); // TODO: Change the autogenerated stub
        }

        public function list_attributes()
        {
            parent::list_attributes(); // TODO: Change the autogenerated stub
        }

        public function get_image_id()
        {
            return parent::get_image_id(); // TODO: Change the autogenerated stub
        }

        public function get_image($size = 'shop_thumbnail', $attr = array())
        {
            return parent::get_image($size, $attr); // TODO: Change the autogenerated stub
        }

        public function get_formatted_name()
        {
            return parent::get_formatted_name(); // TODO: Change the autogenerated stub
        }
    }
}